/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import fleet.FleetCoord;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author pet1
 */
public class DriverPanel extends javax.swing.JPanel
{
    private FleetCoord flCoord;
    private Set<Object> keysVehicles;    
    private DefaultComboBoxModel vehicleList;    
    private Gui mainFrame;
    private boolean breaks;
    private boolean lights;
    private boolean mirrors;   
    
    /**
     * Creates driver panel
     * @param frameIn
     * @param flCoordIn 
     */
    DriverPanel(Gui frameIn, FleetCoord flCoordIn)
    {
        flCoord = flCoordIn;        
        vehicleList = new DefaultComboBoxModel();               
        mainFrame = frameIn;                                              
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroupBrakes1 = new javax.swing.ButtonGroup();
        buttonGroupLights2 = new javax.swing.ButtonGroup();
        buttonGroupMirrors3 = new javax.swing.ButtonGroup();
        jTabbedPaneDriver = new javax.swing.JTabbedPane();
        jPanelReport = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanelMakeReportDefectDetails = new javax.swing.JPanel();
        jScrollPaneMakeReportDefectDetails = new javax.swing.JScrollPane();
        jTextAreaMakeReportDefectDetails = new javax.swing.JTextArea();
        jLabelDefectDetails = new javax.swing.JLabel();
        jLabelMakeReport = new javax.swing.JLabel();
        jPanelMakeReportInform = new javax.swing.JPanel();
        jComboBoxVehicles = new javax.swing.JComboBox<>();
        jTextFieldName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jXDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabelDate = new javax.swing.JLabel();
        jTextFieldMileage = new javax.swing.JTextField();
        jLabelMileage = new javax.swing.JLabel();
        jPanelMakeReportCheckBoxes = new javax.swing.JPanel();
        jLabeGoodCondition = new javax.swing.JLabel();
        jPanelComponentsNames = new javax.swing.JPanel();
        jLabelBrakes1 = new javax.swing.JLabel();
        jLabelLights2 = new javax.swing.JLabel();
        jLabelMirrrors3 = new javax.swing.JLabel();
        jPanelYesNo = new javax.swing.JPanel();
        jPanelYesNo1 = new javax.swing.JPanel();
        jRadioButtonYes1 = new javax.swing.JRadioButton();
        jRadioButtonNo1 = new javax.swing.JRadioButton();
        jPanelYesNo2 = new javax.swing.JPanel();
        jRadioButtonYes2 = new javax.swing.JRadioButton();
        jRadioButtonNo2 = new javax.swing.JRadioButton();
        jPanelYesNo3 = new javax.swing.JPanel();
        jRadioButtonYes3 = new javax.swing.JRadioButton();
        jRadioButtonNo3 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonConfirm1 = new javax.swing.JButton();
        jButtonReset1 = new javax.swing.JButton();
        jPanelMessages = new javax.swing.JPanel();
        jPanelSignOutDriver = new javax.swing.JPanel();
        jButtonDriverSignOut = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanelMakeReportDefectDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextAreaMakeReportDefectDetails.setColumns(20);
        jTextAreaMakeReportDefectDetails.setLineWrap(true);
        jTextAreaMakeReportDefectDetails.setRows(5);
        jTextAreaMakeReportDefectDetails.setWrapStyleWord(true);
        jScrollPaneMakeReportDefectDetails.setViewportView(jTextAreaMakeReportDefectDetails);

        jLabelDefectDetails.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDefectDetails.setText("Defect details");

        javax.swing.GroupLayout jPanelMakeReportDefectDetailsLayout = new javax.swing.GroupLayout(jPanelMakeReportDefectDetails);
        jPanelMakeReportDefectDetails.setLayout(jPanelMakeReportDefectDetailsLayout);
        jPanelMakeReportDefectDetailsLayout.setHorizontalGroup(
            jPanelMakeReportDefectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMakeReportDefectDetailsLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabelDefectDetails)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(jPanelMakeReportDefectDetailsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPaneMakeReportDefectDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanelMakeReportDefectDetailsLayout.setVerticalGroup(
            jPanelMakeReportDefectDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMakeReportDefectDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDefectDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneMakeReportDefectDetails)
                .addGap(16, 16, 16))
        );

        jLabelMakeReport.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMakeReport.setText("Pre use check report");

        jPanelMakeReportInform.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jComboBoxVehicles.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jComboBoxVehiclesMouseClicked(evt);
            }
        });
        jComboBoxVehicles.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBoxVehiclesActionPerformed(evt);
            }
        });

        jTextFieldName.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Vehicle");

        jLabel3.setText("Name");

        jXDatePicker.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jXDatePickerActionPerformed(evt);
            }
        });

        jLabelDate.setText("Date");

        jTextFieldMileage.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextFieldMileageActionPerformed(evt);
            }
        });

        jLabelMileage.setText("Mileage");

        javax.swing.GroupLayout jPanelMakeReportInformLayout = new javax.swing.GroupLayout(jPanelMakeReportInform);
        jPanelMakeReportInform.setLayout(jPanelMakeReportInformLayout);
        jPanelMakeReportInformLayout.setHorizontalGroup(
            jPanelMakeReportInformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMakeReportInformLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelMakeReportInformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMakeReportInformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addComponent(jLabelDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabelMileage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMakeReportInformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxVehicles, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelMakeReportInformLayout.createSequentialGroup()
                        .addGroup(jPanelMakeReportInformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldName)
                            .addComponent(jXDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(jTextFieldMileage))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelMakeReportInformLayout.setVerticalGroup(
            jPanelMakeReportInformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMakeReportInformLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelMakeReportInformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMakeReportInformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMileage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMileage))
                .addGap(18, 18, 18)
                .addGroup(jPanelMakeReportInformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanelMakeReportInformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDate))
                .addContainerGap())
        );

        jPanelMakeReportCheckBoxes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabeGoodCondition.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabeGoodCondition.setText("Item in good condition   yes/no");

        jPanelComponentsNames.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabelBrakes1.setText("Brakes");

        jLabelLights2.setText("Lights");

        jLabelMirrrors3.setText("Mirrors");

        javax.swing.GroupLayout jPanelComponentsNamesLayout = new javax.swing.GroupLayout(jPanelComponentsNames);
        jPanelComponentsNames.setLayout(jPanelComponentsNamesLayout);
        jPanelComponentsNamesLayout.setHorizontalGroup(
            jPanelComponentsNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComponentsNamesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelComponentsNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLights2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMirrrors3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabelBrakes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelComponentsNamesLayout.setVerticalGroup(
            jPanelComponentsNamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComponentsNamesLayout.createSequentialGroup()
                .addComponent(jLabelBrakes1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabelLights2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMirrrors3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelYesNo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanelYesNo1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        buttonGroupBrakes1.add(jRadioButtonYes1);
        jRadioButtonYes1.setText("yes");
        jRadioButtonYes1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonYes1ActionPerformed(evt);
            }
        });

        buttonGroupBrakes1.add(jRadioButtonNo1);
        jRadioButtonNo1.setText("no");
        jRadioButtonNo1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonNo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelYesNo1Layout = new javax.swing.GroupLayout(jPanelYesNo1);
        jPanelYesNo1.setLayout(jPanelYesNo1Layout);
        jPanelYesNo1Layout.setHorizontalGroup(
            jPanelYesNo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelYesNo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonYes1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanelYesNo1Layout.setVerticalGroup(
            jPanelYesNo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelYesNo1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelYesNo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonYes1)
                    .addComponent(jRadioButtonNo1)))
        );

        jPanelYesNo2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        buttonGroupLights2.add(jRadioButtonYes2);
        jRadioButtonYes2.setText("yes");
        jRadioButtonYes2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonYes2ActionPerformed(evt);
            }
        });

        buttonGroupLights2.add(jRadioButtonNo2);
        jRadioButtonNo2.setText("no");
        jRadioButtonNo2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonNo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelYesNo2Layout = new javax.swing.GroupLayout(jPanelYesNo2);
        jPanelYesNo2.setLayout(jPanelYesNo2Layout);
        jPanelYesNo2Layout.setHorizontalGroup(
            jPanelYesNo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelYesNo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonYes2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelYesNo2Layout.setVerticalGroup(
            jPanelYesNo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelYesNo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButtonNo2)
                .addComponent(jRadioButtonYes2))
        );

        jPanelYesNo3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        buttonGroupMirrors3.add(jRadioButtonYes3);
        jRadioButtonYes3.setText("yes");
        jRadioButtonYes3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonYes3ActionPerformed(evt);
            }
        });

        buttonGroupMirrors3.add(jRadioButtonNo3);
        jRadioButtonNo3.setText("no");
        jRadioButtonNo3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonNo3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelYesNo3Layout = new javax.swing.GroupLayout(jPanelYesNo3);
        jPanelYesNo3.setLayout(jPanelYesNo3Layout);
        jPanelYesNo3Layout.setHorizontalGroup(
            jPanelYesNo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelYesNo3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonYes3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonNo3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelYesNo3Layout.setVerticalGroup(
            jPanelYesNo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelYesNo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButtonNo3)
                .addComponent(jRadioButtonYes3))
        );

        javax.swing.GroupLayout jPanelYesNoLayout = new javax.swing.GroupLayout(jPanelYesNo);
        jPanelYesNo.setLayout(jPanelYesNoLayout);
        jPanelYesNoLayout.setHorizontalGroup(
            jPanelYesNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelYesNoLayout.createSequentialGroup()
                .addGroup(jPanelYesNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelYesNo1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelYesNo3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelYesNo2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanelYesNoLayout.setVerticalGroup(
            jPanelYesNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelYesNoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanelYesNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanelYesNo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelYesNo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelMakeReportCheckBoxesLayout = new javax.swing.GroupLayout(jPanelMakeReportCheckBoxes);
        jPanelMakeReportCheckBoxes.setLayout(jPanelMakeReportCheckBoxesLayout);
        jPanelMakeReportCheckBoxesLayout.setHorizontalGroup(
            jPanelMakeReportCheckBoxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMakeReportCheckBoxesLayout.createSequentialGroup()
                .addGroup(jPanelMakeReportCheckBoxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMakeReportCheckBoxesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelComponentsNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelYesNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMakeReportCheckBoxesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabeGoodCondition)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanelMakeReportCheckBoxesLayout.setVerticalGroup(
            jPanelMakeReportCheckBoxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMakeReportCheckBoxesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabeGoodCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMakeReportCheckBoxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelYesNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelComponentsNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jButtonConfirm1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonConfirm1.setText("Confirm");
        jButtonConfirm1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonConfirm1ActionPerformed(evt);
            }
        });

        jButtonReset1.setText("Reset");
        jButtonReset1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonReset1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButtonReset1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(jButtonConfirm1)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReset1)
                    .addComponent(jButtonConfirm1))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMakeReport, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelMakeReportInform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelMakeReportCheckBoxes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanelMakeReportDefectDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMakeReport, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelMakeReportInform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelMakeReportCheckBoxes, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelMakeReportDefectDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanelReportLayout = new javax.swing.GroupLayout(jPanelReport);
        jPanelReport.setLayout(jPanelReportLayout);
        jPanelReportLayout.setHorizontalGroup(
            jPanelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );
        jPanelReportLayout.setVerticalGroup(
            jPanelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(850, Short.MAX_VALUE))
        );

        jTabbedPaneDriver.addTab("Report", jPanelReport);

        javax.swing.GroupLayout jPanelMessagesLayout = new javax.swing.GroupLayout(jPanelMessages);
        jPanelMessages.setLayout(jPanelMessagesLayout);
        jPanelMessagesLayout.setHorizontalGroup(
            jPanelMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
        );
        jPanelMessagesLayout.setVerticalGroup(
            jPanelMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1297, Short.MAX_VALUE)
        );

        jTabbedPaneDriver.addTab("Messages", jPanelMessages);

        jButtonDriverSignOut.setText("Sign out");
        jButtonDriverSignOut.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonDriverSignOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSignOutDriverLayout = new javax.swing.GroupLayout(jPanelSignOutDriver);
        jPanelSignOutDriver.setLayout(jPanelSignOutDriverLayout);
        jPanelSignOutDriverLayout.setHorizontalGroup(
            jPanelSignOutDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignOutDriverLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButtonDriverSignOut)
                .addContainerGap(625, Short.MAX_VALUE))
        );
        jPanelSignOutDriverLayout.setVerticalGroup(
            jPanelSignOutDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignOutDriverLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jButtonDriverSignOut)
                .addContainerGap(1154, Short.MAX_VALUE))
        );

        jTabbedPaneDriver.addTab("Sign out", jPanelSignOutDriver);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTabbedPaneDriver))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDriverSignOutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonDriverSignOutActionPerformed
    {//GEN-HEADEREND:event_jButtonDriverSignOutActionPerformed
        mainFrame.removeDriverPanel();
    }//GEN-LAST:event_jButtonDriverSignOutActionPerformed

    private void jXDatePickerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jXDatePickerActionPerformed
    {//GEN-HEADEREND:event_jXDatePickerActionPerformed

    }//GEN-LAST:event_jXDatePickerActionPerformed

    private void jComboBoxVehiclesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBoxVehiclesActionPerformed
    {//GEN-HEADEREND:event_jComboBoxVehiclesActionPerformed

    }//GEN-LAST:event_jComboBoxVehiclesActionPerformed

    private void jComboBoxVehiclesMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jComboBoxVehiclesMouseClicked
    {//GEN-HEADEREND:event_jComboBoxVehiclesMouseClicked

    }//GEN-LAST:event_jComboBoxVehiclesMouseClicked

    private void jRadioButtonYes1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonYes1ActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonYes1ActionPerformed
        breaks = true; 
    }//GEN-LAST:event_jRadioButtonYes1ActionPerformed

    private void jRadioButtonNo1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonNo1ActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonNo1ActionPerformed
        breaks = false;
    }//GEN-LAST:event_jRadioButtonNo1ActionPerformed

    private void jRadioButtonYes2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonYes2ActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonYes2ActionPerformed
       lights = true;
    }//GEN-LAST:event_jRadioButtonYes2ActionPerformed

    private void jRadioButtonNo2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonNo2ActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonNo2ActionPerformed
        lights = false;
    }//GEN-LAST:event_jRadioButtonNo2ActionPerformed

    private void jRadioButtonYes3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonYes3ActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonYes3ActionPerformed
        mirrors = true;
    }//GEN-LAST:event_jRadioButtonYes3ActionPerformed

    private void jRadioButtonNo3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonNo3ActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonNo3ActionPerformed
        mirrors = false;
    }//GEN-LAST:event_jRadioButtonNo3ActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldNameActionPerformed
    {//GEN-HEADEREND:event_jTextFieldNameActionPerformed
   
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jButtonReset1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonReset1ActionPerformed
    {//GEN-HEADEREND:event_jButtonReset1ActionPerformed
        resetPreCheckReportForm();
    }//GEN-LAST:event_jButtonReset1ActionPerformed

    private void jButtonConfirm1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonConfirm1ActionPerformed
    {//GEN-HEADEREND:event_jButtonConfirm1ActionPerformed
        makePreCheckReportForm();
        resetPreCheckReportForm();
    }//GEN-LAST:event_jButtonConfirm1ActionPerformed

    private void jTextFieldMileageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldMileageActionPerformed
    {//GEN-HEADEREND:event_jTextFieldMileageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMileageActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupBrakes1;
    private javax.swing.ButtonGroup buttonGroupLights2;
    private javax.swing.ButtonGroup buttonGroupMirrors3;
    private javax.swing.JButton jButtonConfirm1;
    private javax.swing.JButton jButtonDriverSignOut;
    private javax.swing.JButton jButtonReset1;
    private javax.swing.JComboBox<String> jComboBoxVehicles;
    private javax.swing.JLabel jLabeGoodCondition;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBrakes1;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelDefectDetails;
    private javax.swing.JLabel jLabelLights2;
    private javax.swing.JLabel jLabelMakeReport;
    private javax.swing.JLabel jLabelMileage;
    private javax.swing.JLabel jLabelMirrrors3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelComponentsNames;
    private javax.swing.JPanel jPanelMakeReportCheckBoxes;
    private javax.swing.JPanel jPanelMakeReportDefectDetails;
    private javax.swing.JPanel jPanelMakeReportInform;
    private javax.swing.JPanel jPanelMessages;
    private javax.swing.JPanel jPanelReport;
    private javax.swing.JPanel jPanelSignOutDriver;
    private javax.swing.JPanel jPanelYesNo;
    private javax.swing.JPanel jPanelYesNo1;
    private javax.swing.JPanel jPanelYesNo2;
    private javax.swing.JPanel jPanelYesNo3;
    private javax.swing.JRadioButton jRadioButtonNo1;
    private javax.swing.JRadioButton jRadioButtonNo2;
    private javax.swing.JRadioButton jRadioButtonNo3;
    private javax.swing.JRadioButton jRadioButtonYes1;
    private javax.swing.JRadioButton jRadioButtonYes2;
    private javax.swing.JRadioButton jRadioButtonYes3;
    private javax.swing.JScrollPane jScrollPaneMakeReportDefectDetails;
    private javax.swing.JTabbedPane jTabbedPaneDriver;
    private javax.swing.JTextArea jTextAreaMakeReportDefectDetails;
    private javax.swing.JTextField jTextFieldMileage;
    private javax.swing.JTextField jTextFieldName;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker;
    // End of variables declaration//GEN-END:variables

    /** 
     * Remove element from the displayed list.
     * @param key 
     */
    void remove(String key) //1+ managerPanel
    {
        vehicleList.removeElement(key);
    }
              
    /**
     * Adds all vehicles to combo box for driver to select one, in Report tab. 
     */ 
    public void addAllVehiclesToCombo()  
    {
        removeAllElementsComboBox();
        jComboBoxVehicles.setModel(vehicleList);
        Set<String> allKeys = flCoord.getVehicles().keySet();        
        
        for (String each : allKeys)
        {
           vehicleList.addElement(each);   
        }        
    } 
                   
    /**
     * Removes all vehicles from driver's combo box, in Report tab.
     */
    public void removeAllElementsComboBox()
    {
        jComboBoxVehicles.removeAllItems();
    }
    
    /**
     * Resets form in Report tab.
     */
    public void resetPreCheckReportForm() 
    {
        jComboBoxVehicles.removeAllItems();
        jTextFieldName.setText("");  
        jTextFieldMileage.setText("");
        jTextAreaMakeReportDefectDetails.setText("");
        jXDatePicker.setDate(null);                
        buttonGroupBrakes1.clearSelection();
        buttonGroupLights2.clearSelection();
        buttonGroupMirrors3.clearSelection(); 
        addAllVehiclesToCombo();
    }
    
    /**
     * Records data from the form, by creating new report that is added to the coordinating object. 
     * New report that is added to the coordinating object.
     */
    public void makePreCheckReportForm()
    {            
        String regN = jComboBoxVehicles.getSelectedItem().toString(); 
        String name = jTextFieldName.getText();
        String defectDetails = jTextAreaMakeReportDefectDetails.getText();        
        int mileage = Integer.parseInt(jTextFieldMileage.getText());                 
        Date jXDate = jXDatePicker.getDate();                
        LocalDate regServiceDate = LocalDateTime.ofInstant(jXDate.toInstant(), ZoneId.systemDefault()).toLocalDate();  
        flCoord.saveAddReport(regN, name, mileage, regServiceDate, breaks, lights, mirrors, defectDetails);                                 
    }     
}
