/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import fleet.FleetCoord;
import fleet.ScheduledService;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;

/**
 *
 * @author Peter Lesko
 */
public class MechanicPanel extends javax.swing.JPanel
{
    private Gui mainFrame;
    private FleetCoord flCoord;
    private DefaultListModel listModelMechNames;
    private DefaultListModel listModelJobAssigments;
    private DefaultListModel listModelTypeOfService;
    private DefaultListModel listModelDefectedItems;
        
    /**
     * Creates new form MechanicPanel
     */
    MechanicPanel(Gui frameIn, FleetCoord flCoordIn)
    {
        mainFrame = frameIn;    
        flCoord = flCoordIn;
        listModelMechNames = new DefaultListModel(); 
        listModelJobAssigments = new DefaultListModel();
        listModelTypeOfService = new DefaultListModel();        
        listModelDefectedItems = new DefaultListModel(); 
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPaneMechanic = new javax.swing.JTabbedPane();
        jPanelJobAssigment = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPanelMechNames = new javax.swing.JScrollPane();
        jListMechNames = new javax.swing.JList<>();
        jLabelMechanics = new javax.swing.JLabel();
        jScrollPanelJobAssigment = new javax.swing.JScrollPane();
        jListJobAssigments = new javax.swing.JList<>();
        jLabelJobAssigments = new javax.swing.JLabel();
        jButtonUpdateJobAssigments = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldRegNo = new javax.swing.JTextField();
        jLabelRegNo = new javax.swing.JLabel();
        jScrollPanelTypeOfService = new javax.swing.JScrollPane();
        jListTypeOfService = new javax.swing.JList<>();
        jLabelTypeOfService = new javax.swing.JLabel();
        jScrollPaneDefectedItems = new javax.swing.JScrollPane();
        jListDefectedItems = new javax.swing.JList<>();
        jLabelDefectedItems = new javax.swing.JLabel();
        jTextAreaDefectDetails = new javax.swing.JTextArea();
        jLabelShowDefectDetails = new javax.swing.JLabel();
        jPanelDefectsReporting = new javax.swing.JPanel();
        jPanelSpareParts = new javax.swing.JPanel();
        jPanelSignOut = new javax.swing.JPanel();
        jButtonSignOut = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jListMechNames.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                jListMechNamesValueChanged(evt);
            }
        });
        jScrollPanelMechNames.setViewportView(jListMechNames);

        jLabelMechanics.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMechanics.setText("Mechanics");

        jListJobAssigments.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                jListJobAssigmentsValueChanged(evt);
            }
        });
        jScrollPanelJobAssigment.setViewportView(jListJobAssigments);

        jLabelJobAssigments.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelJobAssigments.setText("Job assigments");

        jButtonUpdateJobAssigments.setText("Update job assigments");
        jButtonUpdateJobAssigments.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonUpdateJobAssigmentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPanelMechNames, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMechanics))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPanelJobAssigment, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelJobAssigments))
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonUpdateJobAssigments)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMechanics)
                    .addComponent(jLabelJobAssigments))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPanelMechNames, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jScrollPanelJobAssigment))
                .addGap(18, 18, 18)
                .addComponent(jButtonUpdateJobAssigments)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextFieldRegNo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextFieldRegNoActionPerformed(evt);
            }
        });

        jLabelRegNo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelRegNo.setText("Registration no.");

        jListTypeOfService.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                jListTypeOfServiceValueChanged(evt);
            }
        });
        jScrollPanelTypeOfService.setViewportView(jListTypeOfService);

        jLabelTypeOfService.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTypeOfService.setText("Type of service");

        jListDefectedItems.setForeground(new java.awt.Color(255, 51, 51));
        jListDefectedItems.addContainerListener(new java.awt.event.ContainerAdapter()
        {
            public void componentRemoved(java.awt.event.ContainerEvent evt)
            {
                jListDefectedItemsComponentRemoved(evt);
            }
        });
        jListDefectedItems.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                jListDefectedItemsValueChanged(evt);
            }
        });
        jScrollPaneDefectedItems.setViewportView(jListDefectedItems);

        jLabelDefectedItems.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDefectedItems.setText("Defected items");

        jTextAreaDefectDetails.setEditable(false);
        jTextAreaDefectDetails.setColumns(20);
        jTextAreaDefectDetails.setLineWrap(true);
        jTextAreaDefectDetails.setRows(5);
        jTextAreaDefectDetails.setWrapStyleWord(true);

        jLabelShowDefectDetails.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelShowDefectDetails.setText("Defect details");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTypeOfService)
                    .addComponent(jLabelRegNo)
                    .addComponent(jScrollPanelTypeOfService, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneDefectedItems, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDefectedItems, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelShowDefectDetails)
                    .addComponent(jTextAreaDefectDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegNo)
                    .addComponent(jLabelDefectedItems, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelShowDefectDetails))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTypeOfService)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPanelTypeOfService, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextAreaDefectDetails)
                    .addComponent(jScrollPaneDefectedItems))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelJobAssigmentLayout = new javax.swing.GroupLayout(jPanelJobAssigment);
        jPanelJobAssigment.setLayout(jPanelJobAssigmentLayout);
        jPanelJobAssigmentLayout.setHorizontalGroup(
            jPanelJobAssigmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJobAssigmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanelJobAssigmentLayout.setVerticalGroup(
            jPanelJobAssigmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJobAssigmentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelJobAssigmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jTabbedPaneMechanic.addTab("Job assigment", jPanelJobAssigment);

        javax.swing.GroupLayout jPanelDefectsReportingLayout = new javax.swing.GroupLayout(jPanelDefectsReporting);
        jPanelDefectsReporting.setLayout(jPanelDefectsReportingLayout);
        jPanelDefectsReportingLayout.setHorizontalGroup(
            jPanelDefectsReportingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
        );
        jPanelDefectsReportingLayout.setVerticalGroup(
            jPanelDefectsReportingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        jTabbedPaneMechanic.addTab("Defects reporting", jPanelDefectsReporting);

        javax.swing.GroupLayout jPanelSparePartsLayout = new javax.swing.GroupLayout(jPanelSpareParts);
        jPanelSpareParts.setLayout(jPanelSparePartsLayout);
        jPanelSparePartsLayout.setHorizontalGroup(
            jPanelSparePartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
        );
        jPanelSparePartsLayout.setVerticalGroup(
            jPanelSparePartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        jTabbedPaneMechanic.addTab("Spare parts", jPanelSpareParts);

        jButtonSignOut.setText("Sign out");
        jButtonSignOut.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonSignOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSignOutLayout = new javax.swing.GroupLayout(jPanelSignOut);
        jPanelSignOut.setLayout(jPanelSignOutLayout);
        jPanelSignOutLayout.setHorizontalGroup(
            jPanelSignOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignOutLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButtonSignOut)
                .addContainerGap(583, Short.MAX_VALUE))
        );
        jPanelSignOutLayout.setVerticalGroup(
            jPanelSignOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignOutLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButtonSignOut)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jTabbedPaneMechanic.addTab("Sign out", jPanelSignOut);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneMechanic, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 202, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPaneMechanic, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(259, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSignOutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonSignOutActionPerformed
    {//GEN-HEADEREND:event_jButtonSignOutActionPerformed
        mainFrame.removeMechanicPanel();
    }//GEN-LAST:event_jButtonSignOutActionPerformed

    private void jListMechNamesValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_jListMechNamesValueChanged
    {//GEN-HEADEREND:event_jListMechNamesValueChanged

        if(!evt.getValueIsAdjusting() && jListMechNames.getSelectedValue() != null)        
              // prevents, action listener to fire twice, when clicked and uncliked && checks the selected
              // regNo is not null, otherwise listeneer causes exception when clearing the jList.
        {
            resetJobDetails();
            listModelJobAssigments.clear();      
            showJobAssigments(jListMechNames.getSelectedValue());
        }        
    }//GEN-LAST:event_jListMechNamesValueChanged

    private void jButtonUpdateJobAssigmentsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonUpdateJobAssigmentsActionPerformed
    {//GEN-HEADEREND:event_jButtonUpdateJobAssigmentsActionPerformed
        resetJobDetails();
        showMechanics();
    }//GEN-LAST:event_jButtonUpdateJobAssigmentsActionPerformed

    private void jListJobAssigmentsValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_jListJobAssigmentsValueChanged
    {//GEN-HEADEREND:event_jListJobAssigmentsValueChanged
        if(!evt.getValueIsAdjusting() && jListJobAssigments.getSelectedValue() != null)        
              // prevents, action listener to fire twice, when clicked and uncliked && checks the selected
              // regNo is not null, otherwise listeneer causes exception when clearing the jList.
        {
            showDetailsOfService();
        }
    }//GEN-LAST:event_jListJobAssigmentsValueChanged

    private void jTextFieldRegNoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldRegNoActionPerformed
    {//GEN-HEADEREND:event_jTextFieldRegNoActionPerformed

    }//GEN-LAST:event_jTextFieldRegNoActionPerformed

    private void jListTypeOfServiceValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_jListTypeOfServiceValueChanged
    {//GEN-HEADEREND:event_jListTypeOfServiceValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jListTypeOfServiceValueChanged

    private void jListDefectedItemsValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_jListDefectedItemsValueChanged
    {//GEN-HEADEREND:event_jListDefectedItemsValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jListDefectedItemsValueChanged

    private void jListDefectedItemsComponentRemoved(java.awt.event.ContainerEvent evt)//GEN-FIRST:event_jListDefectedItemsComponentRemoved
    {//GEN-HEADEREND:event_jListDefectedItemsComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jListDefectedItemsComponentRemoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSignOut;
    private javax.swing.JButton jButtonUpdateJobAssigments;
    private javax.swing.JLabel jLabelDefectedItems;
    private javax.swing.JLabel jLabelJobAssigments;
    private javax.swing.JLabel jLabelMechanics;
    private javax.swing.JLabel jLabelRegNo;
    private javax.swing.JLabel jLabelShowDefectDetails;
    private javax.swing.JLabel jLabelTypeOfService;
    private javax.swing.JList<String> jListDefectedItems;
    private javax.swing.JList<String> jListJobAssigments;
    private javax.swing.JList<String> jListMechNames;
    private javax.swing.JList<String> jListTypeOfService;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelDefectsReporting;
    private javax.swing.JPanel jPanelJobAssigment;
    private javax.swing.JPanel jPanelSignOut;
    private javax.swing.JPanel jPanelSpareParts;
    private javax.swing.JScrollPane jScrollPaneDefectedItems;
    private javax.swing.JScrollPane jScrollPanelJobAssigment;
    private javax.swing.JScrollPane jScrollPanelMechNames;
    private javax.swing.JScrollPane jScrollPanelTypeOfService;
    private javax.swing.JTabbedPane jTabbedPaneMechanic;
    private javax.swing.JTextArea jTextAreaDefectDetails;
    private javax.swing.JTextField jTextFieldRegNo;
    // End of variables declaration//GEN-END:variables

    /**
     * After specific job assignment is selected it displays the details of that job assignment. 
     */
    public void showDetailsOfService()
    {
        Map<Integer, ScheduledService> scheduledServices = flCoord.getScheduledServices();     //gets all scheduled services 
        ScheduledService schedule = scheduledServices.get(jListJobAssigments.getSelectedValue());    // service schedule that is selected in jobs assignemnts.
        jTextFieldRegNo.setText(schedule.getRegNo());         

        jListTypeOfService.setModel(listModelTypeOfService);                      
        listModelTypeOfService.clear();
        
        if(schedule.getRegulServiceChBox()){listModelTypeOfService.addElement("Regular service");}
        if(schedule.getCVRTChBox()){listModelTypeOfService.addElement("CVRT service");}                
                
        if(schedule.getReportDefectsChBox())
        {
            listModelTypeOfService.addElement("Reported defects");
            
            jListDefectedItems.setModel(listModelDefectedItems);  
            listModelDefectedItems.clear();
            List<String> defectedItems = schedule.getDefectedItems();
            for (String each : defectedItems)
            {
                listModelDefectedItems.addElement(each);
            }
            
            jTextAreaDefectDetails.setText(schedule.getDefectDetails());
        }
    }
         
    /**
     * If the name of the mechanic is selected it displays list of jobs assignments for the selected mechanic. 
     * @param mechanicIn 
     */    
    public void showJobAssigments(String mechanicIn)
    {
        listModelJobAssigments.clear();   
        listModelTypeOfService.clear();
        
        jListJobAssigments.setModel(listModelJobAssigments);
        Map<Integer, ScheduledService> scheduledServices = flCoord.getScheduledServices();   //gets collection of all scheduled services
        
        for(Integer eachKey : scheduledServices.keySet())  // iterates through keys in scheduled services 
        {
            ScheduledService schedule = scheduledServices.get(eachKey);    // variable is assigned to one scheduled service.        
            
            for (String eachMechanic : schedule.getMechanics())    // loop through array of mechanics in specific schedules
            {                         
                if (mechanicIn.equals(eachMechanic))  
                {                   
                    listModelJobAssigments.addElement(schedule.getID());
                }
            } 
        }
    }
           
    /**
     * Display names of mechanics that had been assigned to a service job.
     */
    public void showMechanics()
    {
        Map<Integer, ScheduledService> scheduledServices = flCoord.getScheduledServices();  //gets collection of all scheduled services
        jListMechNames.setModel(listModelMechNames);                

        for(Integer each : scheduledServices.keySet())  // iterates through keys in scheduled services 
        {
            ScheduledService schedule = scheduledServices.get(each);  // variable is assigned to one scheduled service.     
                        
            for (String eachMechanic : schedule.getMechanics())    // loop through array of mechanics in specific schedules
            {              
                if (!listModelMechNames.contains(eachMechanic))
                {
                   listModelMechNames.addElement(eachMechanic);                               
                }
            } 
        }
    }    
       
    /**
     * After list of mechanics is updated or new mechanic selected, it clears other windows. 
     */
    public void resetJobDetails()
    {
        listModelJobAssigments.clear();
        jTextFieldRegNo.setText("");
        listModelTypeOfService.clear();
        listModelDefectedItems.clear();
        jTextAreaDefectDetails.setText("");
    }                
}
